Feature/#6 알림 목록
boostcampwm-2022/android01-UCMC pull request #128
Opened 2022-12-05 02:51 UTC by Hyunji99Choi

## 개요
받은 알림을 목록으로 확인 가능

## 작업사항
- 알림 목록

## 변경된 부분
- nav_main
- string
- build

## 실행 화면

https://user-images.githubusercontent.com/59998983/205538817-86236078-2109-4a90-aa41-2c84a7e9da6e.mp4

## 특이사항
- paging 3 라이브러리 사용
- 현재 알림 목록의 예약 정보에 대해서는 세부 데이터를 가져오지 못한다 -> 고쳐야함..!!!

2022-12-05 04:40 UTC, minseonglove approved these changes
잘햇서요

2022-12-05 04:40 UTC, minseonglove commented on buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
> +            add(Paging.KTX)
페이징은 안드로이드 라이브러리인데 여기 있어도 괜찮은가요?

2022-12-05 04:40 UTC, minseonglove commented on presentation/src/main/java/com/gta/presentation/ui/notification/NotificationListFragment.kt
> +                        }
clickListener 초기화는 변수 선언 때 겸사겸사 해줘도 좋겠네요

2022-12-05 04:40 UTC, minseonglove commented on domain/src/main/java/com/gta/domain/usecase/notification/GetNotificationsInfoUseCase.kt
> +    }
저는 paging 라이브러리를 안써봐서 그런데 List를 받아서 Presentation에서 PagingData로 만들어주는 방법은 없나요?

2022-12-05 04:40 UTC, minseonglove commented on domain/src/main/java/com/gta/domain/model/Notification.kt
> +    licensePlate = "---",
번호판의 기본값을 빈값 대신 짝대기로 넣은 이유가 있나요?

2022-12-05 05:06 UTC, ldh019 commented on domain/src/main/java/com/gta/domain/usecase/notification/GetNotificationsInfoUseCase.kt
> +    }
이걸 생각을 못했네요,,, 페이징 데이터 라는 타입으로 감싸주어야 아래쪽에서 PagingAdapter가 인식을 하는것으로 알고 있는데 이것 참 몹시 문제인걸요?

2022-12-05 06:48 UTC, Hyunji99Choi commented on buildSrc/src/main/java/com/gta/buildsrc/Dependencies.kt
> +            add(Paging.KTX)
이 라이브러리가.. PagingData를  정의하려면 꼭 필요하더라고요..

2022-12-05 06:49 UTC, Hyunji99Choi commented on presentation/src/main/java/com/gta/presentation/ui/notification/NotificationListFragment.kt
> +                        }
그렇네요 이 clickListener은 변하는게 없으니까..!

2022-12-05 06:50 UTC, Hyunji99Choi commented on presentation/src/main/java/com/gta/presentation/ui/notification/NotificationListFragment.kt
> +                        }
그렇네요 이 clickListener은 변하는게 없으니까..!

2022-12-05 06:51 UTC, Hyunji99Choi commented on domain/src/main/java/com/gta/domain/usecase/notification/GetNotificationsInfoUseCase.kt
> +    }
그러..니까요... 예시나 예제는 전보 domain 영역이 없는 레포지토리 구조인데 저희는 도메인이 있어서 이런 에로사항이 발생합니다..

2022-12-05 06:52 UTC, Hyunji99Choi commented on domain/src/main/java/com/gta/domain/model/Notification.kt
> +    licensePlate = "---",
현재 예약id를 통해 세부 정보를 가져오는 부분에서 시행착오를 겪다보니 눈에 띄게 설정해둔다는게 저렇게 됫습니다.. 버그 fix가 되면 아마.. 정보없음이 될것 같네요

2022-12-05 15:22 UTC, minseonglove commented on domain/src/main/java/com/gta/domain/model/Notification.kt
> +    licensePlate = "---",
그럭구만

2022-12-05 18:43 UTC, juyoung0520 commented on presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
> +    }
invalidateOptionsMenu() 호출하면 이게 호출 되군요

2022-12-05 18:44 UTC, juyoung0520 approved these changes
Paging 할 때 참고하겠습니다 ㅎㅎ

2022-12-06 00:43 UTC, ldh019 commented on data/src/main/java/com/gta/data/repository/NotificationRepositoryImpl.kt
> +        Timber.d("notifyInfo 번호판 ${notifyInfo.licensePlate}")
로그는 지워주세용

2022-12-06 00:43 UTC, ldh019 commented on data/src/main/java/com/gta/data/source/CarDataSource.kt
> +            .toObject(Car::class.java)
오 이렇게 해도 잘 바꿔지는군요 좋아

2022-12-06 00:44 UTC, ldh019 commented on data/src/main/java/com/gta/data/source/NotificationPagingSource.kt
> +            val nextPage = dataSource.getNotificationInfoNextItem(userId, lastDocumentSnapshot)
어라 아직 덜 고쳐졌나요 널이 없네

2022-12-06 00:45 UTC, ldh019 commented on domain/build.gradle.kts
> +    kotlin("kapt")
도메인에 kapt가 왜 필요할까요...?

2022-12-06 00:45 UTC, ldh019 commented on domain/src/main/java/com/gta/domain/usecase/notification/GetNotificationsInfoUseCase.kt
> +    }
해결 완료 됐죠? ㅎㅎ

2022-12-06 00:46 UTC, ldh019 commented on presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
> +            }
그러고 보니 맵 프래그먼트에서 알림을 어디다 둘지 말을 안나눴군요

2022-12-06 00:47 UTC, ldh019 commented on presentation/src/main/java/com/gta/presentation/ui/notification/NotificationListFragment.kt
> +                            Timber.d("수락 요청")
팀버!

2022-12-06 00:49 UTC, ldh019 requested changes
아마 아직 다른거 한다고 덜 고친거 같아요..? 고치고 다시 알려주십숑

2022-12-06 02:15 UTC, Hyunji99Choi commented on presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
> +    }
그렇습니다..!

2022-12-06 02:17 UTC, Hyunji99Choi commented on data/src/main/java/com/gta/data/source/NotificationPagingSource.kt
> +            val nextPage = dataSource.getNotificationInfoNextItem(userId, lastDocumentSnapshot)
paging...! 어렵다~

2022-12-06 02:19 UTC, Hyunji99Choi commented on presentation/src/main/java/com/gta/presentation/ui/MainActivity.kt
> +            }
그래서 일단은 표시 안되게 했읍니다

2022-12-06 02:36 UTC, Hyunji99Choi commented on domain/build.gradle.kts
> +    kotlin("kapt")
허업.. 바로 지우겠습니다

2022-12-06 02:43 UTC, ldh019 approved these changes
아 깔끔해요 좋습니다~

2022-12-06 02:49 UTC, merged