Fix: #118 예약 화면 수정
boostcampwm-2022/android01-UCMC pull request #129
Opened 2022-12-05 05:44 UTC by juyoung0520

## 개요
예약 화면 살짝 수정

## 작업사항
- 수락된, 보류중, 대여중인 상태의 예약만 달력에 가져오기
- 선택된 예약 시간 자정으로 수정

## 변경된 부분
- ReservationViewModel
- ReservationDataSource

## 실행 화면

## 특이사항
- DatePicker에 타임존 설정 같은 머 그런게 없는거 같더라구여

2022-12-05 06:36 UTC, minseonglove approved these changes
변경사항엔 없지만 101번째 라인에 getCarRentInfoUseCase를 collect하는 부분에서 scope에 collectJob이 설정되어있지 않네요

2022-12-05 06:36 UTC, minseonglove commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            )
이거 In쓰면 또 10개 이슈에 걸리지 않나요?

2022-12-05 06:36 UTC, minseonglove commented on presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
> +import java.util.*
와일드 임포트는 범죄입니다.

2022-12-05 06:46 UTC, ldh019 commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            )
이게 무슨 일이야아아ㅏ아

2022-12-05 06:47 UTC, ldh019 commented on presentation/src/main/java/com/gta/presentation/ui/reservation/ReservationViewModel.kt
> +            set(Calendar.HOUR_OF_DAY, 0)
아마 이렇게 해도 괜찮을겁니다 사용자 디바이스 기준으로 잡힐거라

2022-12-05 06:50 UTC, ldh019 requested changes
whereIn... 없애주세요... 곤란합니다...

2022-12-05 08:52 UTC, juyoung0520 commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            )
미안하다~~

2022-12-05 08:54 UTC, juyoung0520 commented
이게 머지 된다면 디비 수정이 일어날 겁니다.

2022-12-05 08:55 UTC, minseonglove approved these changes

2022-12-05 08:55 UTC, minseonglove commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            .whereGreaterThanOrEqualTo("state", ReservationState.PENDING.state)
숫자가 짱이네요

2022-12-05 09:03 UTC, ldh019 commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            .whereGreaterThanOrEqualTo("state", ReservationState.PENDING.state)
역시 체고여

2022-12-05 09:04 UTC, ldh019 approved these changes
좋아요 좋습니다

2022-12-06 01:04 UTC, Hyunji99Choi approved these changes
고생하셨습니다!

2022-12-06 01:04 UTC, Hyunji99Choi commented on data/src/main/java/com/gta/data/source/ReservationDataSource.kt
> +            .whereGreaterThanOrEqualTo("state", ReservationState.PENDING.state)
굿

2022-12-06 01:37 UTC, merged